name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '17']

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Compile
      run:
        ./mill -i __.compile

    - name: Test
      run:
        ./mill -i --debug itest
